### ISSUE TITLE
[Recomendation] Add more options for villager trading Overrides

### ISSUE THREAD

**Issue by TH3N3WN00B** [PretzelJohn/VillagerTradeLimiter#5]
Add an option to use emerald blocks instead of items

Add an option to use both trading slots, for example use 2 stacks of emeralds instead of one for 1 mending book

Remove the caps sensitive lock for when disabling a villager profession

**Comment by PretzelJohn** [comment]
Hey, I believe the first two are already possible. You can replace all items in any trade by adding Item1, Item2, and Result to an override. For example, this will change a librarian's name tag trade to 128 emerald blocks -> 2 name tags:

```
Overrides:
  name_tag:
    Item1:
      Material: emerald_block
      Amount: 64
    Item2:
      Material: emerald_block
      Amount: 64
    Result:
      Material: name_tag
      Amount: 2
```

Is there another issue you're referring to here?

For the caps sensitive disabled professions and items, I can fix that in the next update. Right now, you just have to make the professions lower-case in the config.
